(() => {
  'use strict';
  const rooms=[{id:'living',name:'客厅',yaw:.65,pitch:-.08,fov:83,design:'living-design-v3',thumb:'living-thumb-v3'},{id:'dining',name:'餐厅',yaw:0,design:'dining-design-v3',thumb:'dining-thumb-v3'},{id:'kitchen',name:'厨房',yaw:0,pitch:-.10,fov:78,design:'kitchen-design-v3',thumb:'kitchen-thumb-v3'},{id:'bedroom',name:'主卧',yaw:0},{id:'south',name:'南次卧',yaw:-1.75}];
  const $=id=>document.getElementById(id),canvas=$('panorama'),gl=canvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:true});
  let current=0,mode='design',yaw=rooms[0].yaw,pitch=0,fov=75,split=.5,rotating=false,requestId=0,frameId=0,lastTime=0;
  const pointers=new Map(),cache=new Map(); let textures=[],storageOpen=false,activeView='library';
  if(!gl){$('status').textContent='此浏览器未开启全景显示，请在 Chrome、Edge 或 Safari 中打开。';return;}
  const vs='attribute vec2 a;varying vec2 v;void main(){v=a;gl_Position=vec4(a,0.,1.);}';
  const fs=`precision highp float;varying vec2 v;uniform sampler2D original;uniform sampler2D design;uniform float aspect;uniform float lens;uniform float yaw;uniform float pitch;uniform int mode;uniform float split;uniform float width;void main(){vec3 d=normalize(vec3(v.x*aspect*lens,v.y*lens,1.));float c=cos(pitch),s=sin(pitch);d=vec3(d.x,c*d.y+s*d.z,-s*d.y+c*d.z);c=cos(yaw);s=sin(yaw);d=vec3(c*d.x+s*d.z,d.y,-s*d.x+c*d.z);vec2 uv=vec2(.5+atan(d.x,d.z)/6.28318530718,.5-asin(clamp(d.y,-1.,1.))/3.14159265359);vec4 a=texture2D(original,uv),b=texture2D(design,uv);gl_FragColor=mode==1?a:mode==2?(gl_FragCoord.x/width<split?a:b):b;}`;
  function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
  const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
  const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);
  const uniforms={};['original','design','aspect','lens','yaw','pitch','mode','split','width'].forEach(n=>uniforms[n]=gl.getUniformLocation(program,n));gl.uniform1i(uniforms.original,0);gl.uniform1i(uniforms.design,1);
  function draw(){if(textures.length<2)return;const ratio=Math.min(window.devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);textures.forEach((t,i)=>{gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,t);});gl.uniform1f(uniforms.aspect,w/h);gl.uniform1f(uniforms.lens,Math.tan(fov*Math.PI/360));gl.uniform1f(uniforms.yaw,yaw);gl.uniform1f(uniforms.pitch,pitch);gl.uniform1i(uniforms.mode,mode==='original'?1:mode==='compare'?2:0);gl.uniform1f(uniforms.split,split);gl.uniform1f(uniforms.width,w);gl.drawArrays(gl.TRIANGLES,0,6);}
  function texture(src){if(cache.has(src))return cache.get(src);const p=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,im);resolve(t);};im.onerror=()=>{cache.delete(src);reject(Error('图片加载失败'));};im.src=src;});cache.set(src,p);return p;}
  async function loadRoom(index){const rid=++requestId;current=index;activeView='library';storageOpen=false;$('storage').disabled=true;updateStorage();stopRotate();const r=rooms[index];yaw=r.yaw;pitch=r.pitch||0;fov=r.fov||75;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view==='library')));$('status').textContent=`正在载入${r.name}全景…`;$('load-error').hidden=true;$('room-name').textContent=r.name;$('room-index').textContent=`0${index+1} / 05`;document.querySelectorAll('.room-card').forEach((b,i)=>b.setAttribute('aria-current',String(i===index)));try{const ts=await Promise.all([texture(`assets/${r.id}-original.jpg`),texture(`assets/${r.design||r.id+'-design'}.jpg`)]);if(rid!==requestId)return;textures=ts;draw();$('status').textContent='';$('load-state').textContent='AI 设计稿 · 布局概念预览';canvas.dataset.ready=r.id;canvas.dataset.storage='closed';$('storage').disabled=false;}catch(e){if(rid!==requestId)return;$('status').textContent='';$('load-error').hidden=false;$('load-state').textContent='加载未完成';$('storage').disabled=true;}}
  rooms.forEach((r,i)=>{const button=document.createElement('button');button.className='room-card';button.setAttribute('aria-label',`查看${r.name}全景`);button.setAttribute('aria-current',String(i===0));const im=document.createElement('img');im.src=`assets/${r.thumb||r.id+'-thumb'}.jpg`;im.alt='';const name=document.createElement('strong');name.textContent=r.name;const number=document.createElement('span');number.className='number';number.textContent=`0${i+1}`;button.append(im,name,number);button.addEventListener('click',()=>loadRoom(i));$('rooms').append(button);});
  document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('split-control').hidden=mode!=='compare';updateStorage();draw();}));
  function updateStorage(){ $('living-views').hidden=current!==0; $('storage-controls').hidden=current!==0||mode==='original'||activeView!=='tv'; $('storage').setAttribute('aria-pressed',String(storageOpen)); $('storage').textContent=storageOpen?'关闭柜门':'查看电视收纳'; }
  const views={library:{yaw:.65,pitch:-.08,fov:83},tea:{yaw:2.05,pitch:-.24,fov:91},tv:{yaw:-1.45,pitch:0,fov:91}};
  function focusView(name){activeView=name;updateStorage();stopRotate();yaw=views[name].yaw;pitch=views[name].pitch;fov=views[name].fov;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));draw();}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>focusView(b.dataset.view));
  $('storage').onclick=async()=>{const roomRequest=requestId,next=!storageOpen;const button=$('storage');button.disabled=true;focusView('tv');try{const t=await texture(next?'assets/living-storage-open-v3.jpg':'assets/living-design-v3.jpg');if(current!==0||requestId!==roomRequest)return;textures[1]=t;storageOpen=next;canvas.dataset.storage=next?'open':'closed';$('status').textContent='';updateStorage();draw();}catch{ $('status').textContent='电视收纳画面未能加载，请重试'; }finally{button.disabled=false;}};
  $('split').addEventListener('input',e=>{split=Number(e.target.value)/100;$('split-control').style.setProperty('--split',`${split*100}%`);draw();});
  function zoom(delta){fov=Math.max(35,Math.min(100,fov+delta));draw();}function move(dx,dy=0){yaw+=dx;pitch=Math.max(-1.48,Math.min(1.48,pitch+dy));draw();}
  function stopRotate(){rotating=false;cancelAnimationFrame(frameId);$('rotate').setAttribute('aria-pressed','false');$('rotate').textContent='自动环视';lastTime=0;}
  function tick(t){if(!rotating)return;if(lastTime)yaw+=(t-lastTime)*.00005;lastTime=t;draw();frameId=requestAnimationFrame(tick);}
  $('rotate').addEventListener('click',()=>{if(rotating){stopRotate();return;}rotating=true;$('rotate').setAttribute('aria-pressed','true');$('rotate').textContent='停止环视';frameId=requestAnimationFrame(tick);});
  $('left').onclick=()=>{stopRotate();move(-.2);};$('right').onclick=()=>{stopRotate();move(.2);};$('zoom-in').onclick=()=>zoom(-8);$('zoom-out').onclick=()=>zoom(8);$('reset').onclick=()=>{if(current===0){focusView('library');return;}stopRotate();yaw=rooms[current].yaw;pitch=rooms[current].pitch||0;fov=rooms[current].fov||75;draw();};$('retry').onclick=()=>loadRoom(current);
  canvas.addEventListener('pointerdown',e=>{stopRotate();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);if(pointers.size===1){const rad=fov*Math.PI/180/canvas.clientHeight;move(-(e.clientX-old.x)*rad,(e.clientY-old.y)*rad);}else if(pointers.size===2){const other=Array.from(pointers.entries()).find(([id])=>id!==e.pointerId)[1];const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>0&&after>0)zoom(fov*(before/after-1));}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});});
  const end=e=>pointers.delete(e.pointerId);canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('lostpointercapture',end);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.sign(e.deltaY)*4);},{passive:false});
  window.addEventListener('keydown',e=>{if($('details').open||e.target.matches('input,button'))return;let used=true;if(e.key==='ArrowLeft')move(-.1);else if(e.key==='ArrowRight')move(.1);else if(e.key==='ArrowUp')move(0,.1);else if(e.key==='ArrowDown')move(0,-.1);else if(e.key==='+'||e.key==='=')zoom(-5);else if(e.key==='-')zoom(5);else used=false;if(used){e.preventDefault();stopRotate();}});
  $('clean').onclick=()=>{const clean=$('viewer').classList.toggle('clean-view');$('clean').textContent=clean?'恢复界面':'净览';$('clean').setAttribute('aria-pressed',String(clean));$('clean').setAttribute('aria-label',clean?'恢复全景操作界面':'隐藏界面查看完整全景');};
  $('info').onclick=()=>{$('details').showModal();};$('close-info').onclick=()=>{$('details').close();};$('details').addEventListener('click',e=>{if(e.target===$('details')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
  $('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('viewer').requestFullscreen)await $('viewer').requestFullscreen();else{$('status').textContent='可通过浏览器菜单进入全屏';}}catch{$('status').textContent='可通过浏览器菜单进入全屏';}};
  document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏';draw();});new ResizeObserver(draw).observe(canvas);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopRotate();});if(matchMedia('(pointer:coarse)').matches)$('view-hint').textContent='单指环视 · 双指缩放';
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('status').textContent='全景显示已暂停，请刷新页面恢复。';stopRotate();});loadRoom(0);
})();
